/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './App.tsx',
    './index.tsx',
    './constants.ts',
    './types.ts',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
    './services/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        bg: {
          page: 'var(--bg-page)',
          card: 'var(--bg-card)',
          surface: 'var(--bg-surface)',
          subtle: 'var(--bg-subtle)',
          dark: 'var(--bg-page)',
        },
        text: {
          main: 'var(--text-main)',
          muted: 'var(--text-muted)',
          inverted: 'var(--text-inverted)',
        },
        accent: {
          primary: 'var(--accent-primary)',
          secondary: 'var(--accent-secondary)',
        },
        border: {
          DEFAULT: 'var(--border-subtle)',
          subtle: 'var(--border-subtle)',
          strong: 'var(--border-strong)',
        },
        muted: 'var(--text-muted)',
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        marquee: 'marquee 25s linear infinite',
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        shine: 'shine 8s linear infinite',
        'grid-flow': 'gridFlow 20s linear infinite',
        'grid-flow-lg': 'gridFlowLg 30s linear infinite',
        'grid-flow-sm': 'gridFlowSm 15s linear infinite',
        'slide-in-right': 'slideInRight 0.4s ease-out forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        fadeInUp: {
          '0%': { opacity: 0, transform: 'translateY(20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        shine: {
          '0%': { backgroundPosition: '200% center' },
          '100%': { backgroundPosition: '-200% center' },
        },
        gridFlow: {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '40px 40px' },
        },
        gridFlowLg: {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '64px 64px' },
        },
        gridFlowSm: {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '32px 32px' },
        },
        slideInRight: {
          '0%': { opacity: 0, transform: 'translateX(100%)' },
          '100%': { opacity: 1, transform: 'translateX(0)' },
        },
      },
    },
  },
  safelist: [
    'text-emerald-400',
    'text-blue-400',
    'text-purple-400',
    'text-pink-400',
    'text-orange-400',
    'text-cyan-400',
    'text-yellow-400',
    'text-red-400',
    'text-indigo-400',
    'bg-emerald-400',
    'bg-blue-400',
    'bg-purple-400',
    'bg-pink-400',
    'bg-orange-400',
    'bg-cyan-400',
    'bg-yellow-400',
    'bg-red-400',
    'bg-indigo-400',
    'from-emerald-400',
    'from-blue-400',
    'from-purple-400',
    'from-pink-400',
    'from-orange-400',
    'from-cyan-400',
    'from-yellow-400',
    'from-red-400',
    'from-indigo-400',
    'border-emerald-400',
    'border-blue-400',
    'border-purple-400',
    'border-pink-400',
    'border-orange-400',
    'border-cyan-400',
    'border-yellow-400',
    'border-red-400',
    'border-indigo-400',
  ],
};
